✨ feat(yggdrasil): add `什么是外置登录？`
LittleSkinChina/manual-ng pull request #11
Opened 2024-08-28 14:15 UTC by SerinaNya

在 `/yggdrasil/` 页面上简单解释了一下

- 什么是外置登录
- 外置登录的基本实现方式
- 与离线登录和正版登录的区别

在 `yggdrasil/client` 页面中新增链接到 `什么是外置登录？` 部分

2024-08-29 17:04 UTC, tnqzh123 requested changes

2024-08-29 17:04 UTC, tnqzh123 commented on docs/yggdrasil/index.md
> +他们会冒充其他玩家进入服务器行偷鸡摸狗之事；零成本的批量账号更是轰炸小型服务器的绝妙武器。
```suggestion
但离线登录的鉴权机制给予了恶意玩家们极大的发挥空间。他们会冒充其他玩家进入服务器行偷鸡摸狗之事，零成本的批量账号更是轰炸小型服务器的绝妙武器。
```

2024-08-29 17:04 UTC, tnqzh123 commented on docs/yggdrasil/index.md
> +因此而头疼的服务器管理员们会为服务器安装诸如 AuthMe 之类的登录插件，以尽可能杜绝上述事项。
可以补充一点登录插件的弊端，比如不允许改名、找回密码繁琐等等

2024-08-29 17:15 UTC, XieXiLin2 requested changes

2024-08-29 17:15 UTC, XieXiLin2 commented on docs/yggdrasil/index.md
> +为了在游戏中能让玩家们欣赏到各自的皮肤，CustomSkinLoader 和 SkinsRestorer 等 Mod 或插件被广泛使用。
语法问题

2024-08-29 17:15 UTC, XieXiLin2 commented on docs/yggdrasil/client.md
> +> 仅仅在客户端使用 LittleSkin 的外置登录服务并不能达到任何效果。
```suggestion
> **仅仅在客户端使用 LittleSkin 的外置登录服务并不能达到任何效果。**
```
bold

2024-08-30 02:52 UTC, SerinaNya commented on docs/yggdrasil/client.md
> +> 仅仅在客户端使用 LittleSkin 的外置登录服务并不能达到任何效果。
不必要。

这一大段想要表述的都是同一个意思。了，加粗其中一两句没啥用。

2024-08-30 09:28 UTC, XieXiLin2 requested changes

2024-08-30 09:28 UTC, XieXiLin2 commented on docs/yggdrasil/index.md
> +对服务器管理员来说，登录插件的配置过程称不上简单。对于玩家来说，改名 / 忘记密码等操作更是繁琐。
```suggestion
对服务器管理员来说，登录插件的配置过程称不上简单。对于玩家来说，改名、忘记密码等操作更是繁琐。
```

2024-08-30 09:32 UTC, tnqzh123 requested changes

2024-08-30 09:32 UTC, tnqzh123 commented on docs/yggdrasil/index.md
> +对服务器管理员来说，登录插件的配置过程称不上简单。对于玩家来说，改名 / 忘记密码等操作更是繁琐。
```suggestion
因此而头疼的服务器管理员们会为服务器安装诸如 AuthMe 之类的登录插件，以尽可能杜绝上述事项。然而，对服务器管理员来说，登录插件的配置过程称不上简单；对于玩家来说，改名 / 忘记密码等操作更是繁琐。
```

突出一点转折关系

2024-08-30 10:03 UTC, XieXiLin2 approved these changes

2024-09-01 14:53 UTC, tnqzh123 approved these changes

2024-09-01 14:53 UTC, merged