添加忘记密码相关FAQ
LittleSkinChina/manual-ng pull request #12
Opened 2024-09-03 03:56 UTC by Paper-white

2024-09-03 04:13 UTC, XieXiLin2 requested changes

2024-09-03 04:13 UTC, XieXiLin2 commented on docs/faq/site.md
> +## 忘记站点密码/如何修改密码 {#}
```suggestion
## 忘记了自己账号的密码？ {#forget-password}
```

2024-09-03 04:13 UTC, XieXiLin2 commented on docs/faq/site.md
> +  - 打开[`个人资料`](https://littleskin.cn/user/profile)页面
这部分建议用 BSSection，找 金** 帮你改。

2024-09-03 04:13 UTC, XieXiLin2 commented on docs/faq/site.md
> +  - 找到`更改密码`模块
同上。

2024-09-03 04:13 UTC, XieXiLin2 commented on docs/faq/site.md
> +  - 输入你的老密码和新密码进行修改
```suggestion
  - 输入你账号目前的密码和您想要的新密码进行修改
```

2024-09-03 04:13 UTC, XieXiLin2 commented on docs/faq/site.md
> +  - 在登录页面账号密码框下侧选择`忘记密码?`按钮
```suggestion
  - 在登录页面账号密码框下侧选择 `忘记密码?` 按钮
```
感觉也可以超链接一下。

2024-09-03 04:13 UTC, XieXiLin2 commented on docs/faq/site.md
> +  - 将邮件里的链接使用浏览器打开 **不要使用内置浏览器访问！！！**
```suggestion
  - 将邮件里的链接使用浏览器打开
     **特别注意：不要使用各种 App 的内置浏览器访问！！！**
```

2024-09-03 04:17 UTC, LeiSureLyYrsc commented on docs/faq/site.md
> +  - 打开[`个人资料`](https://littleskin.cn/user/profile)页面
我问一下，BSSection图标元素包含LittleSkin全部使用的吗？

2024-09-03 04:20 UTC, XieXiLin2 commented
最好不要把 .vscode 文件夹提交上来。

2024-09-03 04:20 UTC, Paper-white commented on docs/faq/site.md
> +  - 打开[`个人资料`](https://littleskin.cn/user/profile)页面
因为BSSection这部分不会玩，所以暂时用自己习惯的方式高亮了）

2024-09-03 04:21 UTC, XieXiLin2 commented on docs/faq/site.md
> +  - 打开[`个人资料`](https://littleskin.cn/user/profile)页面
> 我问一下，BSSection图标元素包含LittleSkin全部使用的吗？

按钮模板，用法建议全仓库搜索 BSSection 自行学习。

2024-09-03 04:21 UTC, Paper-white commented
我还在学怎么整，刚刚自己突然多了个.vscode我也是懵的（

2024-09-03 04:21 UTC, XieXiLin2 commented on docs/faq/site.md
> +  - 打开[`个人资料`](https://littleskin.cn/user/profile)页面
> 因为BSSection这部分不会玩，所以暂时用自己习惯的方式高亮了）

所以让 金** 来不就好了。

2024-09-03 04:23 UTC, XieXiLin2 commented
> 我还在学怎么整，刚刚自己突然多了个.vscode我也是懵的（

删掉然后再次 commit。

2024-09-03 05:58 UTC, LeiSureLyYrsc commented
把site.md的定义改成#forgot-password，这样可以达成联动

2024-09-03 09:28 UTC, SerinaNya requested changes

2024-09-03 09:28 UTC, SerinaNya commented on docs/faq/site.md
> +## 忘记站点密码/如何修改密码 {#forgot-password}
```suggestion
## 忘记/修改密码 {#reset-password}
```

2024-09-03 09:28 UTC, SerinaNya commented on docs/faq/site.md
> +  - 输入你的老密码和你想要修改的新密码进行修改
```suggestion
  - 按页面提示输入你的现有密码和你想要设置的新密码
```

2024-09-03 09:28 UTC, SerinaNya commented on docs/faq/site.md
> +  **特别注意: 不要使用任何APP的内置浏览器直接访问链接！！！**
麻烦解释一下为什么要特别注意这个  不太懂

2024-09-03 09:42 UTC, Paper-white commented on docs/faq/site.md
> +  **特别注意: 不要使用任何APP的内置浏览器直接访问链接！！！**
邮箱app或者QQ内置浏览器直接点击忘记密码的链接，会跳转到仪表盘/登录页面，而非正常的重置密码页面

2024-09-03 09:46 UTC, Paper-white commented on docs/faq/site.md
> +## 忘记站点密码/如何修改密码 {#forgot-password}
此处改为forgot-password是为了和另一个pr做交互（他最下面写了个链接到这里的）
如果改的话另一边也记得改一下

2024-09-04 14:04 UTC, SerinaNya commented
我近期会对文本进行微调，等着

2024-09-05 12:01 UTC, SerinaNya commented on docs/faq/site.md
> +      content: mc skin cape 我的世界 faq littleskin 万用皮肤补丁 csl 外置登录 皮肤站 披风 报错 打不开 加载 不显示 无效的会话 看不见 邮件 邮箱 挂了 密码 忘记密码 无法登陆
```suggestion
      content: mc skin cape 我的世界 faq littleskin 万用皮肤补丁 csl 外置登录 皮肤站 披风 报错 打不开 加载 不显示 无效的会话 看不见 邮件 邮箱 挂了 密码 忘记密码 设置密码 重置密码 无法登陆
```

2024-09-05 13:59 UTC, closed without merging