添加 忘记密码/修改密码 和 账户验证的页面
LittleSkinChina/manual-ng pull request #14
Opened 2024-09-03 05:43 UTC by LeiSureLyYrsc

QQ验证邮箱Webp:/manual-ng-master/docs/newbee/assets/verify-account/QQMail-MainPage-New.webp

忘记密码/修改密码:/manual-ng-master/docs/faq/site.md 最后面

账户验证:/manual-ng-master/docs/verify-account.md

2024-09-03 09:15 UTC, XieXiLin2 commented
will merge after #12 merged.

2024-09-03 09:37 UTC, SerinaNya requested changes

2024-09-03 09:37 UTC, SerinaNya commented on docs/newbee/verify-account.md
> +# 验证账户
语言略显混乱  豪无排版格式可言

总体内容无问题

2024-09-03 09:48 UTC, LeiSureLyYrsc commented on docs/newbee/verify-account.md
> +# 验证账户
我去看一下需要修改的地方，但关于BSSection元素用法麻烦金姐姐处理一下

2024-09-03 10:18 UTC, XieXiLin2 requested changes

2024-09-03 10:18 UTC, XieXiLin2 commented on docs/newbee/verify-account.md
> +1.打开 [<BSSection><FA :icon="faEnvelope" /> QQ邮箱官网</BSSection>](https://mail.qq.com) 页面并登录你的QQ账号，点击查看主题为 <BSSection>LittleSkin</BSSection> 的邮件
不 要 滥 用 BSSection

2024-09-03 10:18 UTC, XieXiLin2 commented on docs/newbee/verify-account.md
> +与上图操作相似，请在各自邮箱网页/APP的 **收件箱** 和 **垃圾箱** 寻找由 <BSSection>LittleSkin</BSSection> 发出来的验证邮件
不 要 滥 用 BSSection

2024-09-03 10:26 UTC, LeiSureLyYrsc commented on docs/newbee/verify-account.md
> +与上图操作相似，请在各自邮箱网页/APP的 **收件箱** 和 **垃圾箱** 寻找由 <BSSection>LittleSkin</BSSection> 发出来的验证邮件
等待金姐姐来改善关于BSSection的问题
麻烦金姐姐了

2024-09-03 10:35 UTC, LeiSureLyYrsc commented
关于 **无法收到邮件** 这个问题，是直接原文写到verify-account好(就是我的初版warning和tip)
还是通过卡片跳转到常见问题好？

2024-09-03 10:38 UTC, SerinaNya commented
> 关于 **无法收到邮件** 这个问题，是直接原文写到verify-account好(就是我的初版warning和tip)
> 还是通过卡片跳转到常见问题好？


通过卡片跳转到常见问题

2024-09-04 14:04 UTC, SerinaNya commented
我近期会对文本进行微调，等着

2024-09-05 12:17 UTC, SerinaNya requested changes
修复了大量格式相关问题

2024-09-05 12:17 UTC, SerinaNya commented on docs/newbee/verify-account.md
> +但你离创建角色到进入游戏的过程还差最后一步:验证你的邮箱！
```suggestion
欢迎加入 LittleSkin 大家庭🎉

看到此处，你应该已经成功注册了 LittleSkin 账号！🎉🎉

但你离创建角色到进入游戏的过程还差最后一步：验证你的邮箱。
```

2024-09-05 12:17 UTC, SerinaNya commented on docs/newbee/verify-account.md
> +:::
```suggestion
> [!IMPORTANT] 注意
> 请始终使用浏览器访问邮件中的链接。
>
> 从手机 QQ 或 QQ 邮箱 APP 内置的浏览器中直接访问链接可能会产生错误。
```

2024-09-05 12:17 UTC, SerinaNya commented on docs/newbee/verify-account.md
> +2. 点击以 <BSSection>LittleSkin</BSSection> 为邮件主题的文件，然后点击邮件里提供的**链接**进入 <BSSection>LittleSkin</BSSection> 的邮箱验证网站
```suggestion
2. 点击以 **LittleSkin** 为邮件主题的文件，然后点击邮件里的链接进入 LittleSkin 的邮箱验证页面
```

2024-09-05 12:17 UTC, SerinaNya commented on docs/newbee/verify-account.md
> +1. 打开 [<BSSection><FA :icon="faEnvelope" /> QQ邮箱官网</BSSection>](https://mail.qq.com) 页面并登录你的QQ账号，点击查看主题为 <BSSection>LittleSkin</BSSection> 的邮件
```suggestion
1. 打开 [<BSSection><FA :icon="faEnvelope" /> QQ 邮箱官网</BSSection>](https://mail.qq.com) 页面并登录你的 QQ 账号，点击查看主题为 **LittleSkin** 的邮件
```

2024-09-05 12:17 UTC, SerinaNya commented on docs/newbee/verify-account.md
> +3. 输入你注册 <BSSection>LittleSkin</BSSection> 对应的邮箱账号，然后点击<BSSection>提交</BSSection>
```suggestion
3. 输入你注册 LittleSkin 时提供的邮箱，然后点击 <BSSection>提交</BSSection> 按钮
```

2024-09-05 12:17 UTC, SerinaNya commented on docs/newbee/verify-account.md
> +   你现在可以进行 [<BSSection><FA :icon="faUsers" /> 创建角色</BSSection>](https://littleskin.cn/user/player) 的步骤啦！
```suggestion
4. 大功告成🎉

  你已成功验证账号！

你现在可以进行 [<BSSection><FA :icon="faUsers" /> 创建角色</BSSection>](https://littleskin.cn/user/player) 的步骤啦！
```

2024-09-05 12:17 UTC, SerinaNya commented on docs/newbee/verify-account.md
> +## 以QQ邮箱(网页版新版):
没必要注明是新版还是旧版

```suggestion
## 以 QQ 邮箱为例
```

2024-09-05 12:17 UTC, SerinaNya commented on docs/newbee/verify-account.md
> +与上图操作相似，请在各自邮箱网页/APP的 **收件箱** 和 **垃圾箱** 寻找由 <BSSection>LittleSkin</BSSection> 发出来的验证邮件
```suggestion
与上述操作相似，请在各自邮箱提供商的网页或 APP 的 **收件箱** 和 **垃圾箱** 寻找由 **LittleSkin** 发出的验证邮件
```

2024-09-05 12:17 UTC, SerinaNya commented on docs/newbee/verify-account.md
> +前去查看如何重设自己的密码
```suggestion
前去了解如何重置自己的密码
```

2024-09-05 13:12 UTC, SerinaNya approved these changes
review @tnqzh123

2024-09-06 13:34 UTC, XieXiLin2 requested changes

2024-09-06 13:34 UTC, XieXiLin2 commented on docs/newbee/assets/verify-account/QQMail-MainPage-New.webp
need better image

2024-09-06 13:34 UTC, XieXiLin2 commented on docs/newbee/verify-account.md
> +1. 打开 [<BSSection><FA :icon="faEnvelope" /> QQ 邮箱官网</BSSection>](https://mail.qq.com) 页面并登录你的 QQ 账号，点击查看主题为 **LittleSkin** 的邮件
```suggestion
1. 打开 [QQ 邮箱官网](https://mail.qq.com) 页面并登录你的 QQ 账号，点击查看主题为 **LittleSkin** 的邮件

```

2024-09-07 16:24 UTC, LeiSureLyYrsc commented on docs/newbee/assets/verify-account/QQMail-MainPage-New.webp
请提供一些关于图片的需求细节条件

2024-09-08 23:10 UTC, SerinaNya approved these changes

2024-09-09 11:51 UTC, XieXiLin2 commented on docs/newbee/assets/verify-account/QQMail-MainPage-New.webp
give up

2024-09-09 13:18 UTC, SerinaNya reviewed
尚可，不强制要求更改

2024-09-09 13:26 UTC, XieXiLin2 requested changes

2024-09-09 13:26 UTC, XieXiLin2 commented on docs/newbee/verify-account.md
> +1. 打开 [QQ 邮箱官网](https://mail.qq.com) 页面并登录你的 QQ 账号，打开 **收件箱-①** 后查看主题为 **LittleSkin-②** 的邮件
```suggestion
1. 打开 [QQ 邮箱官网](https://mail.qq.com) 页面并登录你的 QQ 账号，打开 **收件箱** 后查看发件人为 **LittleSkin** 的邮件
   ![](./assets/verify-account/QQMail-MainPage-New.webp)
```

2024-09-09 13:26 UTC, XieXiLin2 commented on docs/newbee/verify-account.md
> +  你已成功验证账号！
```suggestion
至此，您已成功完成了验证账号的步骤！
```

2024-09-09 13:26 UTC, XieXiLin2 commented on docs/newbee/verify-account.md
> +> 请认准邮件 **发件人** 为 **LittleSkin (no-reply@littlesk.in)**
```suggestion
> - 请始终使用浏览器访问邮件中的链接。
> - 从手机 QQ 或 QQ 邮箱 APP 内置的浏览器中直接访问链接可能会产生错误。
> - 请认准 **发件人** 为 **LittleSkin (no-reply@littlesk.in)** 的邮件，谨防诈骗邮件。
```

2024-09-09 14:25 UTC, LeiSureLyYrsc commented on docs/newbee/assets/verify-account/QQMail-MainPage-New.webp
名字露出去没问题，如果需要修改就提醒一下

2024-09-10 12:09 UTC, SerinaNya approved these changes

2024-09-11 13:05 UTC, tnqzh123 commented on docs/newbee/verify-account.md
> +至此，您已成功完成了验证账号的步骤！
```suggestion
至此，你已成功完成了验证账号的步骤！
```

「您」和「你」不要混用

2024-09-11 13:13 UTC, tnqzh123 requested changes

2024-09-11 13:13 UTC, tnqzh123 commented on docs/newbee/verify-account.md
> +# 验证账户
不是「验证账户」，是「验证邮箱」

两者有着本质上的区别，「验证账户」指的是对 LittleSkin 账户本身进行验证（用户身份认证），而「验证邮箱」指的是验证邮箱可用性

2024-09-11 13:13 UTC, tnqzh123 commented on docs/newbee/verify-account.md
> +2. 点击以 **LittleSkin** 为邮件主题的文件，然后点击邮件里的链接进入 LittleSkin 的邮箱验证页面
```suggestion
2. 点击以 **LittleSkin** 为发件人的邮件，然后点击邮件里的链接进入 LittleSkin 的邮箱验证页面

```

2024-09-11 13:13 UTC, tnqzh123 commented on docs/newbee/verify-account.md
> +至此，您已成功完成了验证账号的步骤！
```suggestion
至此，你已成功完成了验证账号的步骤！
```

「您」和「你」不要混用

2024-09-11 13:13 UTC, tnqzh123 commented on docs/newbee/verify-account.md
> +你现在可以进行 [<BSSection><FA :icon="faUsers" /> 创建角色</BSSection>](https://littleskin.cn/user/player) 的步骤啦！
要不考虑下链接到手册页面？

或者在下面添加个「如何创建角色」的 Card？

2024-09-11 13:17 UTC, XieXiLin2 commented on docs/newbee/verify-account.md
> +你现在可以进行 [<BSSection><FA :icon="faUsers" /> 创建角色</BSSection>](https://littleskin.cn/user/player) 的步骤啦！
```suggestion
你现在可以进行 [<BSSection><FA :icon="faUsers" /> 创建角色</BSSection>](/newbee/player) 的步骤啦！
```

2024-09-11 13:18 UTC, XieXiLin2 commented on docs/newbee/verify-account.md
> +# 验证账户
```suggestion
# 验证邮箱
```

2024-09-11 13:19 UTC, XieXiLin2 requested changes
同步 https://github.com/LittleSkinChina/manual-ng/pull/14#discussion_r1754478741

2024-09-11 13:19 UTC, XieXiLin2 commented on docs/.vitepress/config.mts
> +                { text: '验证账户', link: '/newbee/verify-account' },
```suggestion
                { text: '验证邮箱', link: '/newbee/verify-account' },
```

2024-09-11 13:34 UTC, SerinaNya approved these changes

2024-09-11 13:37 UTC, XieXiLin2 commented on docs/newbee/verify-account.md
> +> - 请认准 **发件人** 为 **LittleSkin (no-reply@littlesk.in)** 的邮件，谨防诈骗邮件。
```suggestion
> - 请认准 **发件人** 为 **LittleSkin (no-reply📧littlesk.in)** 的邮件，谨防诈骗邮件。
```

2024-09-11 13:37 UTC, tnqzh123 commented on docs/newbee/verify-account.md
> +至此，您已成功完成了验证账号的步骤！
> 统一成「您」更好。用户可不是霸王，是「亲爱的可爱的值得尊敬的值得爱惜的」。

我说难听点，我们又不指着用户给我们赚钱，我凭啥要对用户用尊称，是他给我们打钱了还是他帮我们做啥重要的事了

我觉得对平级的人用「您」很怪，不仅是我对别人的称呼，也包括别人对我的称呼，有人称呼我用「您」我会觉得浑身不舒服，我又不是什么道德高尚之人

2024-09-11 13:39 UTC, XieXiLin2 commented on docs/newbee/verify-account.md
> +至此，您已成功完成了验证账号的步骤！
那还真是对不起了。我当用户是上帝。可能我这个人本身就是错误的。

2024-09-11 13:39 UTC, SerinaNya commented on docs/newbee/verify-account.md
> +> - 请认准 **发件人** 为 **LittleSkin (no-reply@littlesk.in)** 的邮件，谨防诈骗邮件。
这个没关系的呀，no-reply 不怕骚扰的

手册中其他地方也是直接写的邮箱，没用使用这个 emoji

2024-09-11 13:42 UTC, XieXiLin2 requested changes
同步 https://github.com/LittleSkinChina/manual-ng/commit/b407107482bd5e2256963ed6fc7e540c587f04ae

2024-09-11 13:42 UTC, XieXiLin2 commented on docs/.vitepress/config.mts
> +                { text: '验证邮箱', link: '/newbee/verify-account' },
```suggestion
                { text: '验证邮箱', link: '/newbee/verify-email' },
```

2024-09-11 13:45 UTC, XieXiLin2 commented on docs/newbee/verify-email.md
> +你现在可以进行 [<BSSection><FA :icon="faUsers" /> 创建角色</BSSection>](/newbee/player) 的步骤啦！
perfor NCard assign @SerinaNya

2024-09-11 13:58 UTC, SerinaNya approved these changes

2024-09-11 14:31 UTC, XieXiLin2 approved these changes

2024-09-11 14:32 UTC, XieXiLin2 commented
note: MUST use squash merge instead of default merge

2024-09-11 15:00 UTC, merged