Add docs for Device Authorization Grant
LittleSkinChina/manual-ng pull request #15
Opened 2024-10-02 14:09 UTC by tnqzh123

2024-10-02 16:20 UTC, XieXiLin2 commented on docs/advanced/oauth2/authorization-code-grant.md
> +| `server_error`    | 服务器内部错误，请联系 LittleSkin 运营组                |
推荐超链接至「联系我们」。

2024-10-02 16:20 UTC, XieXiLin2 commented on docs/advanced/api.md
> +| `Closet.Read` `Closet.ReadWrite` | 读取/读写用户的衣柜收藏       |
```suggestion
| `Player.Read` / `Player.ReadWrite` | 读取/读写用户的角色和对应材质 |
| `Closet.Read` / `Closet.ReadWrite` | 读取/读写用户的衣柜收藏       |
```

2024-10-02 16:20 UTC, tnqzh123 commented
都别急，等我全写完了 Ready for review 了再改

不然我本地一堆冲突，处理起来很麻烦的

2024-10-05 21:02 UTC, tnqzh123 commented
我写完了，你们看着改，改完喊我 Review，别直接合

OpenID Connect 和 ID Token 那段是我故意塞到设备代码流的那个小段下面的，目前我们没有完全实现 OpenID Connect，也只在设备代码流中有返回 ID Token，单独摘出来写成单独一个大段或者一章我感觉不合适

2024-10-06 07:52 UTC, SerinaNya requested changes
@tnqzh123

2024-10-06 07:52 UTC, SerinaNya commented on docs/feature/oauth-for-yggdrasil.md
> +POST https://littleskin.cn/api/yggdrasil/sessionserver/session/minecraft/profiles HTTP/1.1
✏️ 需要更正 API 地址

2024-10-06 07:52 UTC, SerinaNya commented on docs/advanced/api.md
> +POST https://littleskin.cn/api/yggdrasil/sessionserver/session/minecraft/profiles HTTP/1.1
✏️ 需要更正 API 地址

2024-10-06 12:12 UTC, tnqzh123 commented on docs/advanced/oauth2/device-authorization-grant.md
> +应用需要引导用户或直接打开/调用浏览器，访问授权页面。授权页面的的 URL 为上方响应中的 `verification_uri` 或 `verification_uri_complete`。
```suggestion
然后，应用需要引导用户或直接打开 / 调用浏览器，访问授权页面，并按页面提示操作。授权页面的的 URL 为上方响应中的 `verification_uri` 或 `verification_uri_complete`。
```

2024-10-06 12:12 UTC, tnqzh123 commented on docs/advanced/oauth2/index.md
> +对于需要鉴权的 API，需要先向用户请求授权，获取到访问令牌（Access Token）后，再向对应 API 发起请求。
```suggestion
对于需要鉴权的 API，需要先向用户请求授权，获取到访问令牌（Access Token）后，再向对应的 API 发起请求。
```

2024-10-06 12:12 UTC, tnqzh123 commented on docs/advanced/oauth2/index.md
> +在请求需要鉴权的 API 时，将访问令牌作为 Bearer Token 放入 HTTP 请求的 Authorization 头部中，即可完成鉴权。
```suggestion
在请求需要鉴权的 API 时，将访问令牌作为 Bearer Token 放入 HTTP 请求的 Authorization 头中，即可完成鉴权。
```

统一用语

2024-10-06 12:44 UTC, SerinaNya approved these changes

2024-10-06 13:18 UTC, XieXiLin2 approved these changes

2024-10-06 13:42 UTC, fred913 approved these changes

2024-10-07 09:59 UTC, SerinaNya approved these changes

2024-10-09 02:37 UTC, merged