feat: 新增版权保护章节
LittleSkinChina/manual-ng pull request #8
Opened 2024-06-12 09:49 UTC by SerinaNya

1. 将新的页面命名为 **版权保护** `/copyrights`
2. 简单分析「哪些内容分别属于原创、二创、转载」
    
    因为不是很会写所以用 AI 生成了一部分
3. 说明二创和转载可能存在的风险（指未经原作者授权）
4. 在 **上传材质** 章节中同步新增版权保护有关内容

在修改过程中注意到「禁止上传的材质」中部分内容存在落后，进行了更新；部分内容表述不当，稍作了修改

2024-06-12 15:33 UTC, tnqzh123 requested changes

2024-06-12 15:33 UTC, tnqzh123 commented on docs/copyrights.md
> +> LittleSkin 于 2024年6月 新增了<BSSection><FA :icon="faCopyright" /> 材质来源</BSSection>机制，<mark>新上传的材质必须声明其版权</mark>，以尽可能解决皮肤库中的不规范转载现象。
没必要加这段

2024-06-12 15:33 UTC, tnqzh123 commented on docs/copyrights.md
> +- 在创作时 **没有** 直接参考或依赖于其他已有的作品
```suggestion
- 在创作时 **没有** 直接参考或依赖于其他已有的材质
```

2024-06-12 15:33 UTC, tnqzh123 commented on docs/copyrights.md
> +> 若你<mark>在未取得原作者许可的情况下进行转载</mark>，则存在遭到侵权投诉的风险。
```suggestion
> [!WARNING] 关于转载与侵权
> 若你<mark>在未取得原作者许可的情况下进行转载</mark>，则存在收到侵权投诉的风险。
```

2024-06-12 15:33 UTC, tnqzh123 commented on docs/copyrights.md
> +如果你是某个材质的创作者，且该材质在 LittleSkin 上的存在形式不被你认可，你可以向我们提出异议。
```suggestion
如果你是某个材质的原创作者，且该材质在 LittleSkin 上的存在形式不被你认可，你可以向我们提出异议。
```

2024-06-12 15:33 UTC, tnqzh123 commented on docs/copyrights.md
> +✅ 仅当某个材质<mark>符合以下所有条件</mark>时，我们才能够认为这个材质是 **原创材质**：
```suggestion
✅ 仅当某个材质<mark>符合以下所有条件</mark>时，我们才会认为这个材质是 **原创材质**：
```

2024-06-12 15:33 UTC, tnqzh123 commented on docs/copyrights.md
> +- 基于已经存在的作品进行创作
```suggestion
- 基于已经存在的材质进行创作
```

2024-06-12 15:33 UTC, tnqzh123 commented on docs/copyrights.md
> +- 新增的创意元素足够显著
这两条没必要，如果有人就是只想改某个不是很显眼的部分然后自用呢

2024-06-12 15:33 UTC, tnqzh123 commented on docs/copyrights.md
> +> 这主要取决于原作者是否对你的材质提出异议。
```suggestion
> 若你<mark>在未取得原作者许可的情况下进行二创</mark>，根据原作者的意见，你的创作可能会被认定为侵权。
```

2024-06-12 15:33 UTC, tnqzh123 commented on docs/copyrights.md
> +_衍生_ 通常被称为 _二次创作_ 或简称 _二创_。
不应该强行用另一个名词解释，应该解释清楚二创的含义

2024-06-12 15:33 UTC, tnqzh123 commented on docs/copyrights.md
> +⚠️ 若要转载其他材质，以下是必须遵循的规则：
```suggestion
⚠️ 若要转载其他人制作材质，必须遵守以下规则：
```

2024-06-12 15:33 UTC, tnqzh123 commented on docs/copyrights.md
> +在入群时可能需要提供账号有关信息，这依赖于你拥有 LittleSkin 账号
```suggestion
在入群时可能需要提供账号有关信息，这要求你拥有 LittleSkin 账号
```

2024-06-12 15:33 UTC, tnqzh123 commented on docs/newbee/textures.md
> +   >
没必要加这段

2024-06-12 23:13 UTC, SerinaNya commented on docs/copyrights.md
> +_衍生_ 通常被称为 _二次创作_ 或简称 _二创_。
那我把这段话删除了奥，我觉得下面的那个列表里的几条就是解释

2024-06-15 09:45 UTC, gxres042 reviewed
偶然看到的，有几句话写的挺唐。

2024-06-15 09:45 UTC, gxres042 commented on docs/copyrights.md
> +也被简称为 _二创材质_。并不是所有形式的二次创作都能够被认可，对二次创作的界定也较为模糊。
二次创作材质也被简称为二创材质，在这里指对已有的材质进行修改、基于该材质创作其衍生版本等。但是，二次创作的界定较为模糊，且所有形式的二次创作不一定能够得到认可。

2024-06-15 09:45 UTC, gxres042 commented on docs/copyrights.md
> +✅ 仅当某个材质<mark>符合以下所有条件</mark>时，我们才会认为这个材质是 **原创材质**：
可以是：原创材质是其创作者独立完成的、不基于现有材质的全新材质作品。

2024-06-15 15:50 UTC, tnqzh123 requested changes
豆知识：在 Review 中添加语言为 `suggestion` 的代码块可以添加可以生成可以预览 diff 和快速 commit 的 Suggested change

````markdown
```suggestion
二次创作材质也被简称为二创材质，在这里指对已有的材质进行修改、基于该材质创作其衍生版本等。但是，二次创作的界定较为模糊，且所有形式的二次创作不一定能够得到认可。
```
````

点击 Review 编辑器顶栏上的按钮可以快速插入 Suggested change

![image](https://github.com/LittleSkinChina/manual-ng/assets/16630630/8d2780bc-f6f9-4786-9321-a32a322db721)

2024-06-15 15:50 UTC, tnqzh123 commented on docs/copyrights.md
> +✅ 仅当某个材质<mark>符合以下所有条件</mark>时，我们才会认为这个材质是 **原创材质**：
这个感觉应该列清楚点，免得后面产生纠纷

2024-06-15 15:50 UTC, tnqzh123 commented on docs/copyrights.md
> +也被简称为 _二创材质_。并不是所有形式的二次创作都能够被认可，对二次创作的界定也较为模糊。
```suggestion
二次创作材质也被简称为 _二创材质_，在这里指对已有的材质进行修改、基于该材质创作其衍生版本等。但是，二次创作的界定较为模糊，且所有形式的二次创作不一定能够得到认可。
```

2024-06-15 15:50 UTC, tnqzh123 commented on docs/copyrights.md
> +- 与其他已明确原创作者的材质 **不存在** 高相似度
```suggestion
```
高相似度这条我感觉有点问题，比如说不同作者基于同一动漫角色绘制的皮肤，相似度肯定不会低的

而且怎么判断相似度也是问题，你不能让用户去算 Image Hash 或者跑神经网络算相似度，而且这样受各种因素影响也很大，算出来结果不一定能用

我的建议是把这条删掉，然后再想想办法整材质查重

2024-06-15 16:11 UTC, tnqzh123 approved these changes

2024-06-15 16:11 UTC, merged